apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    type: frontend
spec:
  containers:
    - name: container1
      image: httpd
      ports:
        - containerPort: 80
          protocol: TCP
          name: httpport
