# select the base image
FROM httpd

# copy your website files into /usr/local/apache2/htdocs
# param1: path on your local machine
# param2: path of the image
COPY ./index.html /usr/local/apache2/htdocs/
