apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
spec:
  replicas: 5
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      name: pod
      labels:
        name: myapp
    spec:
      containers:
        - name: container1
          image: httpd
          ports:
            - containerPort: 80
